language: android

jdk:
  - oraclejdk8

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-27
    - build-tools-28

    # The SDK version used to compile your project
    - android-28
    - android-27
    - android-24
    - android-21
    - android-14

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository

  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
  - ./gradlew clean; ./gradlew :plugin:uploadArchives; ./gradlew :app:build